# TTS引擎配置
tts_engine: 'indextts'  # 可选项: 'openvoice', 'indextts'

# OpenVoice V2 specific settings
openvoice:
  # OpenVoice模型的根目录
  model_dir: 'OpenVoice'
  # 默认说话人音色（如果未使用参考音频）
  default_se_path: 'OpenVoice/resources/default_se.pth'

# WhisperX specific settings
whisperx:
  # 使用的Whisper模型大小 (e.g., 'tiny', 'base', 'small', 'medium', 'large-v2')
  model: 'large-v2'
  # 是否使用批处理进行转录
  batch_size: 16
  # 计算类型 (e.g., 'float16', 'int8')
  compute_type: 'float16'

# FFmpeg settings
ffmpeg:
  # FFmpeg可执行文件的路径 (如果不在系统PATH中)
  path: 'ffmpeg'